version: '3.1'

services:
  service_mysql:
      image: mysql
      container_name: docker-mysql-container
      restart: 'always'
      environment:
        MYSQL_ROOT_PASSWORD: "123456"
        MYSQL_DATABASE: "sequelize_playground"
        MYSQL_USERNAME: "root"
        MYSQL_PASSWORD: "root"
        MYSQL_PORT: 3306
      volumes:
        - ./database/mysql/bin:/var/lib/mysql
      ports:
        - 3306:3306
      expose:
        - 3306
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
      networks:
        - network_application

  
networks:
  network_application: